gesdinet_jwt_refresh_token:
    # https://github.com/markitosgv/JWTRefreshTokenBundle
    firewall: 'api'

    manager_type: 'orm'
    refresh_token_class: 'App\Security\Entity\RefreshToken'

    single_use: true
    ttl: 2592000 # 30 days

    token_parameter_name: 'refresh_token'
    return_expiration: true
    return_expiration_parameter_name: 'refresh_token_expiration'
