parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Controller/'
            - '../src/Security/Entity/'
            - '../src/Player/Entity/'
